### ISSUE TITLE
Error when trying to authenticate

### ISSUE THREAD

**Issue by jlerman44** [karllhughes/okta-fastapi#2]
I followed these instructions carefully: https://developer.okta.com/blog/2020/12/17/build-and-secure-an-api-in-python-with-fastapi#retrieving-an-access-token-in-fastapi 

But when filling the Authorization form, I get "Auth ErrorError: Internal Server Error" and then in the console I see

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 188, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 137, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./main.py", line 47, in login
    return retrieve_token(
  File "./main.py", line 30, in retrieve_token
    response = httpx.post(url, headers=headers, data=data)
  File "/usr/local/lib/python3.8/site-packages/httpx/_api.py", line 304, in post
    return request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 747, in request
    return self.send(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 831, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 866, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 900, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 934, in _send_single_request
    (status_code, headers, stream, extensions) = transport.handle_request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 179, in handle_request
    status_code, headers, byte_stream, extensions = self._pool.handle_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 230, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 115, in handle_request
    return self.connection.handle_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 69, in handle_request
    ) = self._receive_response(timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 138, in _receive_response
    headers = event.headers.raw_items()
AttributeError: 'list' object has no attribute 'raw_items'

Any idea what I have done wrong?

**Comment by jlerman44** [comment]
Note: I debugged some, and if I use regular old requests package instead of httpx on the following line, the example now works:

https://github.com/karllhughes/okta-fastapi/blob/d3f7784cc4eff758b4caca662a03f4e24d184aae/main.py#L30
